#!/bin/busybox sh

set -o pipefail

mount -n -t proc proc /proc || fatal "Failure mount /proc"
echo 0 > /proc/sys/kernel/printk

mount -n -t devtmpfs devtmpfs /dev || fatal "Failure mount /dev"
mkdir -m 0755 /dev/pts || fatal "Failure create directory /dev/pts with perms 755"
mount -n -t devpts -o gid=5,mode=0620 devpts /dev/pts || fatal "Failure mount /dev/pts"
mount -n -t sysfs sysfs /sys || fatal "Failure mount /dev/pts"
mount -n -t tmpfs -o rw,nodev,mode=755 none /run || fatal "Failure mount /run"

cat <<EOF

        _____ __  __  ___   _   _   ___   _____ 
       |__  / \ \/ / |_ _| | \ | | |_ _| |_   _|
         / /   \  /   | |  |  \| |  | |    | |  
        / /_   /  \   | |  | |\  |  | |    | |  
       /____| /_/\_\ |___| |_| \_| |___|   |_| 

EOF

source /init-base.functions
#source /init-platform.functions

# Set up busybox'es symlinks
/bin/busybox --install -s || fatal "Failure install busybox symlinks"

touch /var/log/lastlog || fatal "Failure create /var/log/lastlog"

ln -s /proc/mounts /etc/mtab || fatal "Failure link /etc/mtab -> /proc/mounts"

# Prepare cleanup script
echo "#!/bin/busybox sh" > /tmp/cleanup.sh
echo >> /tmp/cleanup.sh
echo "set -e" >> /tmp/cleanup.sh
echo >> /tmp/cleanup.sh
echo >> /tmp/cleanup.sh
chmod +x /tmp/cleanup.sh || fatal "Failure make executeble cleanup script /tmp/cleanup.sh"

# Prepare rollback script
echo "#!/bin/busybox sh" > /tmp/rollback.sh
echo >> /tmp/rollback.sh
echo "set -e" >> /tmp/rollback.sh
echo >> /tmp/rollback.sh
echo >> /tmp/rollback.sh
chmod +x /tmp/rollback.sh || fatal "Failure make executeble rollback script /tmp/rollback.sh"

# Kernel command-line
KCMD=$(cat "/proc/cmdline")

echo "Executing commands..."
for PARAM in $KCMD; do
	NAME=$(echo "$PARAM" | awk -F= '{print $1}')
	VALUE=$(echo "$PARAM" | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
	case "$NAME" in
		osfordev_*)
			$NAME "$VALUE" || fatal "Failure execute $NAME $VALUE"
			;;
	esac
	unset NAME
	unset VALUE
done

if [ -x /tmp/cleanup.sh ]; then
	echo "Executing cleanup script..."
	echo
	echo /tmp/cleanup.sh
	echo
	/tmp/cleanup.sh || fatal "Cleanup failed."
fi

# Clean up.
umount -n /sys || fatal "Failure umount /sys"
umount -n /dev/pts || fatal "Failure umount /dev/pts"
umount -n /dev || fatal "Failure umount /dev"

echo 1 > /proc/sys/kernel/printk

umount -n /proc || fatal "Failure umount /proc"

mount -o move /run /newroot/run || fatal "Failure move mount /run to /newroot/run"

# Boot the real thing.
exec switch_root /newroot /sbin/init $@